output   = "app/models"
wipe     = true
no-tests = true
add-enum-types = true

[mysql]
  dbname  = "sampledb"
  host    = "localhost"
  port    = 3306
  user    = "docker"
  pass    = "docker"
  sslmode = "false"